context:
  version: "0.161.0"

package:
  name: codex
  version: ${{ version }}

source:
  url: https://github.com/openai/codex/archive/refs/tags/rust-v${{ version }}.tar.gz
  sha256: aa012b58ce9ae2410a35c4b3e491fe67aa99b134916491efa341c0691508e416
  patches:
    - patches/0001-Set-recursion_limit-to-256-in-codex-chatgpt.patch

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
    file: build

requirements:
  build:
    - python >=3.11
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - just
    - if: linux
      then: pkg-config
    - if: win
      then: m2-sed
  host:
    - if: unix
      then:
        - ripgrep
    - if: linux
      then:
        - openssl <4.0a0
        - libcap
  run:
    - if: unix
      then: ripgrep

tests:
  - script:
      - codex --version
  - package_contents:
      bin:
        - codex
        - codex-code-mode-host
      files:
        - etc/pixi/codex/global-ignore-conda-prefix
        - if: unix
          then:
            - codex-path/rg
            - share/zsh/site-functions/_codex
            - share/bash-completion/completions/codex
            - share/fish/vendor_completions.d/codex.fish

about:
  summary: Lightweight coding agent that runs in your terminal
  homepage: https://github.com/openai/codex
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/openai/codex

extra:
  recipe-maintainers:
    - moritzwilksch
    - zelosleone
    - Hofer-Julian
    - pavelzw
