context:
  name: codex
  version: "0.50.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/openai/codex/archive/refs/tags/rust-v${{ version }}.tar.gz
  sha256: f8b51710a48f0ed2699321cc80f22ac5614c5fa8bc5a7b1f2d3e72d9a38004b3

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
    - openssl

  host:
    - if: unix
      then:
        - openssl

tests:
  - script:
      - codex --version

about:
  summary: Lightweight coding agent that runs in your terminal
  homepage: https://github.com/openai/codex
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
    - zelosleone
    - Hofer-Julian
