context:
  name: codex
  version: "0.1.2505171619"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@openai/codex/-/codex-${{ version }}.tgz
  sha256: 2008d21ff147fbd51c3f533adbc2975c33cd6c65cffad70eddebf74d913703fc

build:
  number: 0
  noarch: generic


requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - codex --version

about:
  summary: Lightweight coding agent that runs in your terminal
  homepage: https://github.com/openai/codex
  license: Apache-2.0
  license_file:
    - third-party-licenses.txt
    - LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
