context:
  version: "0.151.0"

package:
  name: codex
  version: ${{ version }}

source:
  url: https://github.com/openai/codex/archive/refs/tags/rust-v${{ version }}.tar.gz
  sha256: 17f37b9c2f98e00ce297b813355a1b41cd22882c3def89be84a250069bff0a02

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
    file: build

requirements:
  build:
    - python >=3.11
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - just
    - if: linux
      then: pkg-config
    - if: win
      then: m2-sed
  host:
    - if: linux
      then:
        - openssl <4.0a0
        - libcap

tests:
  - script:
      - codex --version
  - package_contents:
      bin:
        - codex
        - codex-code-mode-host
      files:
        - etc/pixi/codex/global-ignore-conda-prefix

about:
  summary: Lightweight coding agent that runs in your terminal
  homepage: https://github.com/openai/codex
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/openai/codex

extra:
  recipe-maintainers:
    - moritzwilksch
    - zelosleone
    - Hofer-Julian
    - pavelzw
