context:
  name: codex
  version: "0.29.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/openai/codex/archive/refs/tags/rust-v${{ version }}.tar.gz
  sha256: 512d4ebd7d63ac826c13bd197e425851b08778500bffbbc5a6b92930715897fb

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
    - openssl

  host:
    - openssl

tests:
  - script:
      - echo "[DEBUG] Test environment info:"
      - echo "Current directory:" & cd
      - echo "Binary location:" & where codex
      - echo "Binary info:" & dir "%PREFIX%\bin\codex.exe"  # [win]
      - echo "Binary info:" && ls -la "$PREFIX/bin/codex"  # [unix]
      - if exist "%PREFIX%\bin\codex.exe" (echo "Binary exists") else (echo "Binary missing")  # [win]
      - test -f "$PREFIX/bin/codex" && echo "Binary exists" || echo "Binary missing"  # [unix]
      - echo "Attempting to run codex --version:"
      - codex --version

about:
  summary: Lightweight coding agent that runs in your terminal
  homepage: https://github.com/openai/codex
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
    - zelosleone
