context:
  name: codex
  version: "0.27.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/openai/codex/releases/download/rust-v${{ version }}/codex-npm-${{ version }}.tgz
  sha256: a2a5af7c2ca7c117c7f2c6856bc89145f2ef3981b4f07cb3bdc51f4cff07455f

build:
  number: 0
  noarch: generic


requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - codex --version

about:
  summary: Lightweight coding agent that runs in your terminal
  homepage: https://github.com/openai/codex
  license: Apache-2.0
  license_file:
    - third-party-licenses.txt

extra:
  recipe-maintainers:
    - moritzwilksch
    - zelosleone
