context:
  name: codex
  version: "0.1.2504221401"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@openai/codex/-/codex-${{ version }}.tgz
  sha256: f04d7581518e8e0665c0ef18c556b37bd1edd40d5100b25397dc0d4493e23571

build:
  number: 0
  noarch: generic


requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - codex --version

about:
  summary: Lightweight coding agent that runs in your terminal
  homepage: https://github.com/openai/codex
  license: Apache-2.0
  license_file:
    - third-party-licenses.txt
    - LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
