context:
  name: codex
  version: "0.28.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/openai/codex/releases/download/rust-v${{ version }}/codex-npm-${{ version }}.tgz
  sha256: 411fba3813bf78dcc69c7c1aa7c02b2f161a4f12e32b48e5f8fbbbc47020669c

build:
  number: 0
  noarch: generic


requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - codex --version

about:
  summary: Lightweight coding agent that runs in your terminal
  homepage: https://github.com/openai/codex
  license: Apache-2.0
  license_file:
    - third-party-licenses.txt

extra:
  recipe-maintainers:
    - moritzwilksch
    - zelosleone
