context:
  name: codex
  version: "0.97.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/openai/codex/archive/refs/tags/rust-v${{ version }}.tar.gz
  sha256: bb5d18c6c6dce0d02a54f09d3f5a7956147cacf611b63c1a0c3d80b6c843c3b9

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
    - openssl

  host:
    - if: unix
      then:
        - openssl

tests:
  - script:
      - codex --version

about:
  summary: Lightweight coding agent that runs in your terminal
  homepage: https://github.com/openai/codex
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
    - zelosleone
    - Hofer-Julian
