context:
  name: codex
  version: "0.1.2505161800"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@openai/codex/-/codex-${{ version }}.tgz
  sha256: 4cf4af6c0f52cc0865d088e1c931f19117009d527b983c676ce6a3615368a146

build:
  number: 0
  noarch: generic


requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - codex --version

about:
  summary: Lightweight coding agent that runs in your terminal
  homepage: https://github.com/openai/codex
  license: Apache-2.0
  license_file:
    - third-party-licenses.txt
    - LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
