context:
  name: codex
  version: "0.1.2504172351"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@openai/codex/-/codex-${{ version }}.tgz
  sha256: 3e7430e7d9e54fb766d438ee660062446bfcada18acbdec2d7fd59a251447ed7

build:
  number: 0
  noarch: generic


requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - codex --version

about:
  summary: Lightweight coding agent that runs in your terminal
  homepage: https://github.com/openai/codex
  license: Apache-2.0
  license_file:
    - third-party-licenses.txt
    - LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
